# Generated by Django 5.2 on 2025-08-18 11:47

import django.utils.timezone
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.TextField(default='admin')),
                ('action', models.TextField(choices=[('загрузка', 'Upload')])),
                ('creation_ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('notification_recipient', models.EmailField(max_length=254)),
                ('status', models.TextField(choices=[('выполняется', 'In Progress'), ('завершен', 'Done'), ('ошибка', 'Failed')])),
                ('destination', models.TextField(choices=[('файлообменник (яндекс)', 'Yandex')])),
                ('source', models.FilePathField(path=pathlib.PureWindowsPath('Z:/НА МОСКВУ/test'))),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
