# Generated by Django 5.2 on 2025-05-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=256)),
                ('sub_time', models.DateTimeField(null=True)),
                ('target_dir', models.TextField()),
                ('client', models.TextField()),
                ('status', models.TextField(default='2')),
            ],
        ),
    ]
