# Generated by Django 5.2 on 2025-08-14 14:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.TextField(default='admin')),
                ('notification_recipient', models.EmailField(max_length=254)),
                ('task_type', models.TextField(choices=[('upload', 'Upload')])),
                ('creation_ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.TextField(choices=[('in progress', 'In Progress'), ('done', 'Done'), ('failed', 'Failed')])),
                ('destination', models.CharField()),
                ('source', models.FilePathField(path='Z:/НА МОСКВУ/test')),
            ],
        ),
    ]
