# Generated by Django 5.2 on 2025-05-05 14:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoloader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='sub_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
